carparts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('cars/', views.cars, name='cars'),
    path('cars/<int:car_id>', views.car, name='car'),
    path('parts/', views.parts, name='parts'),
    path('parts/<int:part_id>', views.part, name='part'),
    path('search/', views.search, name='search'),
    path('new_base/', views.new_base, name='new_base'),
    path('profile/', views.profile_main, name='profile_main'),
    path('profile-edit/', views.profile, name='profile'),
    path('myparts/', views.LoanedPartsByUserListView.as_view(), name='my-parts'),
    path('myparts/new', views.PartByUserCreateView.as_view(), name='my-parts-new'),
    path('myparts/update/<int:pk>', views.PartByUserUpdateView.as_view(), name='my-parts-update'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:part_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('profile_verification/', views.profile_verification, name='profile-verification'),
    path('mycars/', views.LoanedCarsByUserListView.as_view(), name='my-cars'),
    path('mycars/new', views.CarByUserCreateView.as_view(), name='my-cars-new'),
    path('mycars/update/<int:pk>', views.CarByUserUpdateView.as_view(), name='my-cars-update'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
                  path('carparts/', include('carparts.urls')),
                  path('admin/', admin.site.urls),
                  path('', RedirectView.as_view(url='carparts/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

carparts/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


# Create your models here.
class CarModel(models.Model):
    brand = models.CharField('Brand', null=True, max_length=100, help_text='Input Brand example(Ford)')
    model = models.CharField('Model', null=True, max_length=100, help_text='Input Model name example(Focus)')

    def __str__(self):
        return f'{self.brand} {self.model}'


class Car(models.Model):
    car_cover = models.ImageField('Cover', default="part_pics/no-image.jpg", upload_to='covers', null=True)
    car_model = models.ForeignKey('CarModel', on_delete=models.CASCADE, null=True)
    years = models.CharField('Years', max_length=4, null=True, help_text='Input made date example(2020)')
    FUEL_CHOOSE = (
        ('diesel', 'Diesel'),
        ('petrol', 'Petrol'),
        ('electric', 'Electric'),
        ('hybrid', 'Hybrid'),
        ('choose', 'Unknown')
    )

    fuel = models.CharField(
        max_length=20,
        choices=FUEL_CHOOSE,
        blank=True,
        default='choose',
        help_text='Choose Fuel type',
    )

    engine = models.CharField('Engine', max_length=100, help_text='Input Brand example(2.0TDI)')
    engine_code = models.CharField('Engine Code', blank=True, max_length=100, help_text='Input Engine code')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    power = models.IntegerField('Power KW', help_text='Input power example(77)')
    GEARBOX_CHOOSE = (
        ('automatic', 'Automatic'),
        ('manual', 'Manual'),
        ('Unknown', 'Unknown')
    )
    gearbox = models.CharField(
        max_length=20,
        choices=GEARBOX_CHOOSE,
        blank=True,
        default='Unknown',
        help_text='Choose gearbox type',
    )

    gearbox_code = models.CharField('Gearbox Code', max_length=100, blank=True, help_text='Input Gearbox code')
    color = models.CharField('Color', max_length=20, help_text='Input Color Code example(LC5J)')

    BODY_CHOOSE = (
        ('cabriolet', 'Cabriolet'),
        ('coupe', 'Coupe'),
        ('sedan', 'Sedan'),
        ('station', 'Station'),
        ('hatchback', 'Hatchback'),
        ('Unknown', 'Unknown')
    )

    body_type = models.CharField(
        max_length=20,
        choices=BODY_CHOOSE,
        blank=True,
        default="Unknown",
        help_text='Choose body type',
    )
    parts = models.ManyToManyField('Part', blank=True, related_name='cars', help_text='Link parts to this car')

    def __str__(self):
        return f'{self.car_model.brand} {self.car_model.model} {self.years}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.car_cover.path)
        if img.height > 225 or img.width > 400:
            output_size = (400, 225)
            img.thumbnail(output_size)
            img.save(self.car_cover.path)


class Part(models.Model):
    AVAILABLE_CHOOSE = (
        ('Available', 'Available'),
        ('Sold', 'Sold')
    )
    status = models.CharField(
        max_length=20,
        choices=AVAILABLE_CHOOSE,
        blank=True,
        default='Available',
        help_text='Choose part status'
    )
    part_oem = models.CharField('Part OEM', max_length=100, help_text='Input OEM Code example(A1237300705)')
    part_name = models.CharField('Part name', max_length=100, null=True,
                                 help_text='Write part name example(Audi front-driver doors)')
    part_picture = models.ImageField('Cover', default="part_pics/no-image.jpg", upload_to='covers', null=True)
    part_picture_2 = models.ImageField('Cover2', default="part_pics/no-image.jpg", upload_to='covers', null=True,
                                       )
    part_picture_3 = models.ImageField('Cover3', default="part_pics/no-image.jpg", upload_to='covers', null=True,
                                       )
    part_picture_4 = models.ImageField('Cover4', default="part_pics/no-image.jpg", upload_to='covers', null=True,
                                       )
    part_description = models.CharField('Part description', null=True, max_length=250,
                                        help_text='Write part description')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    CONDITION_CHOOSE = (
        ('new', 'NEW'),
        ('used', 'USED'),
        ('damaged', 'DAMAGED')
    )
    condition = models.CharField(
        max_length=20,
        choices=CONDITION_CHOOSE,
        blank=True,
        help_text='Choose condition part',
    )

    SIDE_CHOOSE = (
        ('left', 'Left'),
        ('right', 'Right'),
        ('rear-left', 'Rear-Left'),
        ('rear-right', 'Rear-Right')
    )
    side = models.CharField(
        max_length=20,
        choices=SIDE_CHOOSE,
        blank=True,
        help_text='Choose part side',
    )
    part_type = models.ForeignKey('PartType', on_delete=models.CASCADE, null=False,
                                  help_text='Choose part type')
    price = models.FloatField('Price', help_text='Input part price example(199.99)')

    def __str__(self):
        return f'{self.part_oem}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.part_picture.path)
        if img.height > 225 or img.width > 300:
            output_size = (300, 225)
            img.thumbnail(output_size)
            img.save(self.part_picture.path)


class PartType(models.Model):
    PART_TYPE = (
        ('air_condition', 'Air conditioning-heating system/radiators'),
        ('body_parts', 'Body parts'),
        ('brake_system', 'Brake system'),
        ('electronic_system', 'Electronic system'),
        ('door', 'Door'),
        ('engine', 'Engine'),
        ('front_body', 'Front body parts'),
        ('rear_body', 'Rear body parts'),
        ('front_axle', 'Front axle'),
        ('rear_axle', 'Rear axle'),
        ('fuel_system', 'Fuel mixture system'),
        ('exhaust_system', 'Gas exhaust system'),
        ('gearbox', 'Gearbox/clutch/transmission'),
        ('glass', 'Glass'),
        ('headlight_system', 'Headlight washing/cleaning system'),
        ('lighting_system', 'Lighting system'),
        ('other_parts', 'Other parts'),
        ('wheels', 'Wheels/tires/caps')
    )
    part_type = models.CharField(
        max_length=100,
        choices=PART_TYPE,
        blank=True,
        null=True,
        help_text='Choose part type',
    )

    def __str__(self):
        return f'{self.part_type}'


class ToDoList(models.Model):
    PROGRESS_TYPE = (
        ('new', 'New'),
        ('working', 'Working'),
        ('stuck', 'Stuck'),
        ('pause', 'Pause'),
        ('almost done', 'Almost Done'),
        ('done', 'Done')
    )
    list_progress = models.CharField(
        max_length=100,
        choices=PROGRESS_TYPE,
        blank=True,
        null=True,
        default='new',
        help_text='Progressive',
    )

    name = models.CharField('Name', null=True, max_length=100, help_text='Input name progress')
    comment = models.CharField('Comment', null=True, max_length=100, help_text='Input comment')

    def __str__(self):
        return f'{self.list_progress}'

    class Meta:
        ordering = ['id']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    STATUS_CHOOSE = (
        ('Not verified', 'Not verified'),
        ('Verified', 'Verified')
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOOSE,
        blank=True,
        default='Not verified',
        help_text='Choose profile status'
    )
    cover = models.ImageField(default="profile_pics/no-image.jpg", null=True, upload_to="profile_pics")
    city = models.CharField('City', max_length=100, null=True, blank=True, help_text='Input city name example(Vilnius)')
    address = models.CharField('Address', max_length=100, null=True, blank=True,
                               help_text='Input address example(Verkiu g. 2)')
    phone_number = models.CharField('Phone number', max_length=100, null=True, blank=True,
                                    help_text='Input phone number example(+37062222222)')

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.cover.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.cover.path)


class CartItem(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.part.part_oem}'

carparts/forms.py
from django.contrib.auth.models import User

from .models import Profile, Part, Car
from django import forms


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # this is the magic right here:
        self.fields['email'].label = "E.mail"
        self.fields['first_name'].label = "Name"
        self.fields['last_name'].label = "Last name"
        self.fields[
            'email'].help_text = "Make sure you enter a valid email, otherwise you won't be able to reset your password!"


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['cover', 'city', 'address', 'phone_number']


class UserPartCreateForm(forms.ModelForm):
    class Meta:
        model = Part
        fields = ['status', 'part_picture', 'part_picture_2', 'part_picture_3', 'part_picture_4', 'part_oem',
                  'part_name', 'part_description',
                  'side', 'condition', 'part_type', 'price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['part_picture'].label = "Main Cover"
        self.fields['part_picture_2'].label = "Cover"
        self.fields['part_picture'].help_text = "If will be uploaded 1 img,last 3 will be no img"
        self.fields['part_picture_3'].label = "Cover"
        self.fields['part_picture_4'].label = "Cover"
        self.fields[
            'part_name'].help_text = "Its import for search. (Part-OEM,Car-brand,Car-mark,years,and part name(A1231111 Audi A6 2020 Led Headlight))"
        self.fields['side'].help_text = "If part have side choose, if not leave ----"
        self.fields[
            'part_type'].help_text = "Important to choose part type ,because if you choose body part at part show color code "
        self.fields['price'].help_text = "Write price"


class UserCarCreateForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['car_cover', 'car_model', 'years', 'fuel', 'engine', 'engine_code',
                  'power', 'gearbox', 'gearbox_code', 'color', 'body_type', 'parts']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['car_cover'].label = "Main Cover"
        self.fields['car_model'].label = "Car Model"

carparts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Parts</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand">CarParts Online</a>
            <ul class="navbar-nav mx-2">
                {% if user.is_superuser %}
                <li class="nav-item active"><a class="btn" href="http://127.0.0.1:8000/admin/">Admin panel</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <style>
                    .dropdown {
                        position: relative;
                        display: inline-block;
                    }

                    .dropdown-content {
                        display: none;
                        position: absolute;
                        background-color: #f9f9f9;
                        min-width: 160px;
                        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
                        z-index: 1;
                    }

                    .dropdown-content a {
                        color: black;
                        padding: 12px 16px;
                        text-decoration: none;
                        display: block;
                    }

                    .dropdown-content a:hover {
                        background-color: #f1f1f1;
                    }

                    .dropdown:hover .dropdown-content {
                        display: block;
                    }

                    .dropdown:hover .dropbtn {
                        background-color: #3e8e41;
                    }


                </style>
                <div class="dropdown">
                    <button class="btn">
                        <svg class="bi bi-person" width="1.2em" height="1.2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                        </svg>
                        {{ user.get_username }}
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'profile_main' %}">Profile</a>
                        <a href="{% url 'my-parts' %}">My parts</a>
                        <a href="{% url 'my-cars' %}">My cars</a>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="btn" type="submit">Log out</button>
                        </form>
                    </div>
                </div>
                <li class="nav-item"><a class="btn" href="{% url 'view_cart' %}">Cart</a></li>
                {% else %}
                <li class="nav-item"><a class="btn" href="{% url 'login' %}">Login</a></li>
                <li class="nav-item"><a class="btn" href="{% url 'register' %}">Register</a></li>
                {% endif %}
                <li class="nav-item active"><a class="btn" href="{% url 'index' %}">Home</a></li>
                <li class="nav-item active"><a class="btn" href="{% url 'cars' %}">Cars</a></li>
                <li class="nav-item active"><a class="btn" href="{% url 'parts' %}">Parts</a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
                <input class="form-control me-2" name="query" type="text" placeholder="Search">
                <button class="btn" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="col-sm-10">
        {% block content %}
        {% endblock %}
    </div>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
</body>

</html>

carparts/templates/car.html
{% extends "base.html" %}

{% load static %}
{% block content %}
{% if car.owner == request.user %}
<link rel="stylesheet" href="{% static 'css/click_box.css' %}">
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-cars-update' car.id %}">Edit</a>
</div>
{% endif %}
<div class="container car">
    <h5>{{ car.car_model }} {{car.engine}} {{car.years}}</h5>
    <img src="{{ car.car_cover.url }}" style="margin-bottom: 20px;">
    <hr/>
    <p>Brand: {{ car.car_model.brand }}</p>
    <p>Model: {{ car.car_model.model }}</p>
    <p>Years: {{ car.years }}</p>
    <p>Engine: {{ car.engine }}</p>
    <p>Engine code: {{car.engine_code}}</p>
    <p>Power: {{ car.power }} kw</p>
    <p>Fuel type: {{ car.fuel }}</p>
    <p>Gearbox: {{ car.gearbox }}</p>
    <p>Gearbox code: {{car.gearbox_code}}</p>
    <p>Body type: {{ car.body_type }}</p>
    <p>Car body color: {{ car.color }}</p>
</div>
<hr/>
<h4>Available parts from this car:</h4>
<div class="row">
    {% for part in car.parts.all %}
    {% if part.status == 'Available' %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            <img src="{{ part.part_picture.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-subtitle mb-2 text-muted"><strong>{{ part.part_name }}</strong> {{ part.part_oem }}</h5>
                {% if part.side %}
                <p class="card-text"> Side:
                    {{ part.side }}</p>
                {% endif %}
                <p class="card-text">Price:
                    {{part.price}} €</p>
                <p class="card-text">Condition:
                    {{part.condition}}</p>
                <a class="click-box" href="{% url 'part' part.id %}">More detail. Click here!</a>
                <a class="click-box" href="{% url 'add_to_cart' part.id %}">Add to Cart</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% empty %}
</div>
<p>No information about car parts. Please contact with seller.For detail info.</p>
{% endfor %}
{% endblock %}

carparts/templates/cars.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/click_box.css' %}">
<p>Available cars for parts right now: <strong>{{ cars_count }}</strong></p>
<div class="row">
    {% for car in cars %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            <img src="{{ car.car_cover.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-subtitle mb-2 text-muted"><strong>{{ car.car_model }}</strong> {{ car.years }}
                    {{car.engine}}</h5>
                <p class="card-text"> Fuel type:
                    {{car.fuel}}</p>
                <p class="card-text">Power:
                    {{car.power}} kw</p>
                <p class="card-text">Gearbox:
                    {{car.gearbox}}</p>
                <a class="click-box" href="{% url 'car' car.id %}">More detail. Click here!</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if cars.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
            {% for i in cars.paginator.page_range %}
            {% if cars.number == i %}
            <li class="page-item active">
                <a class="page-link">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

carparts/templates/index.html
{% extends "base.html" %}

{% block content %}
<p>Statistic:</p>
<ul>
    <li><strong>Used car parts online</strong> {{ parts_count }}</li>
    <li><strong>Scraping cars now:</strong> {{ cars_count }}</li>
</ul>
{% endblock %}

carparts/templates/profile-verification.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<p>Your profile is not verified by Administration </p>
<p>Please contact to us!</p>
<p>To start ur journey to sell parts with us!</p>
{% endblock %}

carparts/templates/profile.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<div class="content-section" xmlns="http://www.w3.org/1999/html">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.cover.url }}">
        <div class="media-body">
           <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">E.mail: {{ user.email }}</p>
            <p class="text-secondary">Last time active: {{ user.last_login }}</p>
            <p class="text-secondary">Account created: {{ user.date_joined }}</p>
            <p><a href="{% url 'profile_main'%}"><strong>Back</strong></a></p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile info:</legend>
                {{ u_form|crispy }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Seller info:</legend>
                {{ p_form|crispy }}</fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
       </form>
    </div>
{% endblock content %}

carparts/templates/profile_main.html
{% extends "base.html" %}

{% block content %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.cover.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">E.mail: {{ user.email }}</p>
            <p class="text-secondary">Last time active: {{ user.last_login }}</p>
            <p class="text-secondary">Account created: {{ user.date_joined }}</p>
            <p>Change profile <a href="{% url 'profile'%}"><strong>Click here!</strong></a></p>
        </div>
      </div>
    </div>
{% endblock content %}

carparts/templates/user_car_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add car</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
    </div>
{% endblock content %}

carparts/templates/user_cars.html
{% extends "base.html" %}

{% load static %}
{% block content %}
{% if request.user.profile.status == 'Verified' %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-cars-new' %}">Add Car</a>
</div>
{% endif %}
<h4>My cars</h4>
<p>Available: <strong>{{ cars_count }}</strong></p>
<div class="row">
    {% for car in car_list %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            <img src="{{ car.car_cover.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-subtitle mb-2 text-muted"><strong>{{ car.car_model }}</strong> {{ car.years }}
                    {{car.engine}}</h5>
                <p class="card-text"> Fuel type:
                    {{car.fuel}}</p>
                <p class="card-text">Power:
                    {{car.power}} kw</p>
                <p class="card-text">Gearbox:
                    {{car.gearbox}}</p>
                <a class="click-box" href="{% url 'car' car.id %}">More detail. Click here!</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if cars.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
            {% for i in cars.paginator.page_range %}
            {% if cars.number == i %}
            <li class="page-item active">
                <a class="page-link">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

carparts/templates/user_parts.html
{% extends "base.html" %}

{% load static %}
{% block content %}
{% if request.user.profile.status == 'Verified' %}
<link rel="stylesheet" href="{% static 'css/click_box.css' %}">
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-parts-new' %}">Add new part</a>
</div>
{% endif %}
<h4>My listed parts</h4>
<p>Available: <strong>{{ parts_count }}</strong></p>
<div class="row">
    {% for part in part_list %}
    <div class="col-md-4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm">
            <img src="{{ part.part_picture.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text"><strong> Status: {{ part.status }}</strong></p>
                <h5 class="card-subtitle mb-2 text-muted"><strong>{{ part.part_oem }}</strong> {{ part.part_name }}</h5>
                {% if part.side %}
                <p class="card-text">Side: {{ part.side }}</p>
                {% endif %}
                <p class="card-text">Price: {{ part.price }} €</p>
                <p class="card-text">Condition: {{ part.condition }}</p>
                <a  class="click-box" href="{% url 'part' part.id %}">More detail. Click here!</a>
            </div>
        </div>
    </div>
    {% empty %}
    <p>No parts available.
    <p>Because not listed any parts, or ur account is not verified.</p>
    <p>Please contact to us!</p>
    <p>To start ur journey to sell parts with us!</p>
    {% endfor %}
</div>
<div class="container puslapiai">
    <nav aria-label="Parts pagination">
        {% if page_obj.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}